### PR TITLE
fix Arabic date parsing exception in Android

### PR DESCRIPTION
**Pull request by mostafaac30**
- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [ ] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

I recently submitted a pull request on the Auth0 repository on GitHub regarding an issue with parsing Arabic dates in the auth0_flutter package. The issue was that the package was unable to parse Arabic dates, leading to a FormatException when attempting to convert them to DateTime objects.

To solve this issue, I added a method to the Credentials class that converts Arabic date strings to their English equivalents before parsing them as DateTime objects. This solution allows the package to properly handle Arabic dates, which is particularly important for apps that may be used in Arabic-speaking countries.

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Please can you update the description with more detail into the problem being solved, and how you're solving it. It's quite a large review to go through without knowing the "why".

**Comment by stevehobbsdev** [comment]
Before I start reviewing some high level bits, did you intend to raise this into our package, or was this intended for your own fork?

**Comment by mostafaac30** [comment]
Hello,

I recently submitted a pull request on the Auth0 repository on GitHub regarding an issue with parsing Arabic dates in the auth0_flutter package. The issue was that the package was unable to parse Arabic dates, leading to a FormatException when attempting to convert them to DateTime objects.

To solve this issue, I added a method to the Credentials class that converts Arabic date strings to their English equivalents before parsing them as DateTime objects. This solution allows the package to properly handle Arabic dates, which is particularly important for apps that may be used in Arabic-speaking countries.

I apologize for not providing sufficient detail in the initial pull request description. I have updated the description to include more information about the issue being solved and the solution implemented.

Thank you for your consideration of this pull request.

Best regards,
 Mostafa

**Comment by mostafaac30** [comment]
Thank you for your question. This change was intended to be raised into your package as a pull request to provide support for Arabic date parsing in the Credentials factory constructor. The proposed change adds a parseArabicDate method that can parse Arabic dates and converts them into the English format before creating a DateTime object. This should improve the experience for users who use Arabic dates with your package.

Let me know if you have any further questions or concerns.

**Comment by stevehobbsdev** [comment]
Thanks for the clarification!

**Comment by mostafaac30** [comment]
You're welcome! Thank you for reviewing the PR, I appreciate your time and effort. I apologize for any confusion caused by the unnecessary changes in the files, and I will be more careful in the future. Looking forward to your comments and feedback.

**Pull request closed without merging**
