### PR TITLE
Fix email verified type

### PR DESCRIPTION
**Pull request by itome**
`email_verified` field is sometimes `String` type instead of `bool` ("true" instead of true).
I'm not professional on OIDC so I don't know whether it's always `String` or both `String` and `bool` is allowed.

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes
Supoprt string type `email_verified` payload.

### CODE REVIEW

**Comment by Widcket** [comment]
Hi @itome, thanks for raising this.

Could you please expand on the circumstances where you found `email_verified` came as a string instead of a bool?

**Comment by itome** [comment]
@Widcket I found it with apple login. Google login and Twitter login works correct.

**Review by Widcket — APPROVED** [review]
Thanks @itome! Really appreciate the contribution.

**Review by Widcket — CHANGES_REQUESTED** [review]
@itome the new test is failing:

Screenshot 2023-10-20 at 2 38 27 PM

**Comment by itome** [comment]
@Widcket Sorry to be late. I fixed the test.

**Review by Widcket — APPROVED** [review]
Thanks @itome!

**Comment by Widcket** [comment]
This is now out in [v1.3.1](https://github.com/auth0/auth0-flutter/releases/tag/afpi-v1.3.1).

**Pull request merged**
