### PR TITLE
Fix access token expiry android

### PR DESCRIPTION
**Pull request by poovamraj**
- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

This error is happening because in Java we were parsing the credentials result as **Z** which refers to [timezone](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) parsing in Java

But this was later changed to escape as shown below.

Screenshot 2023-10-12 at 13 38 20

This means we were initially parsing the timestamp as UTC at the dart layer when credentials were retrieved and to be same as that we had to set timezone while saving the credentials.

But after that we have removed parsing timezone by escaping the **Z** with quotes `''`. But we haven't removed the timezone being set in save credentials handler. This caused the time to jump to the offset of UTC.

We have fixed this by removing the timezone in save credentials handler.

### 📎 References
https://github.com/auth0/auth0-flutter/issues/286
https://github.com/auth0/auth0-flutter/pull/162
https://github.com/auth0/auth0-flutter/compare/v1.0.1...main

### 🎯 Testing
Existing unit test has been fixed to avoid this issue

### CODE REVIEW

**Comment by Widcket** [comment]
Wasn't the Z escaped in this PR: https://github.com/auth0/auth0-flutter/pull/238?

**Review by aprzedecki — APPROVED** [review]
Thats a fix we are looking for 👍

**Comment by Widcket** [comment]
In fact, we requested the escaped format:

Screenshot 2023-10-12 at 1 07 04 PM

Are we sure this change won't re-introduce this issue? https://github.com/auth0/auth0-flutter/issues/160

**Comment by poovamraj** [comment]
Yes, escaping it would be the right thing. But while we escaped the timezone "Z" which will parse the date to local time, we have forgotten to remove 

```
format.timeZone = TimeZone.getTimeZone("UTC")
```

Also this would have caused issues for API login and other places since it was set only here and not in the other places where we format date

**Comment by Widcket** [comment]
It'd be great to have a single date formatter (or format string) in the entire Android native layer, to avoid these kinds of issues.

**Comment by joymyr** [comment]
This fixes the token refesh issue for me. Please merge it

**Review by Widcket — APPROVED** [review]

**Comment by aprzedecki** [comment]
Great! Can we release it also on pub.dev ?

**Comment by mng-prophero** [comment]
> Great! Can we release it also on pub.dev ?

We're needing this released as well as it's affecting our users

**Comment by Widcket** [comment]
👋🏼 I expect to cut a release by EOW.

**Pull request merged**
